// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6dDpy_Ag1opwALIujaCl6fWbMdz1lKQ',
    appId: '1:828532925773:web:361cf93c1c95298cbb8304',
    messagingSenderId: '828532925773',
    projectId: 'calories-scanner-2772d',
    authDomain: 'calories-scanner-2772d.firebaseapp.com',
    storageBucket: 'calories-scanner-2772d.appspot.com',
    measurementId: 'G-M626XV7T0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1moqwuSg737mgpQB5dPwoL05Bj0E0-Q',
    appId: '1:828532925773:android:4f39df4e65dfe884bb8304',
    messagingSenderId: '828532925773',
    projectId: 'calories-scanner-2772d',
    storageBucket: 'calories-scanner-2772d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7-Ws-pge9gDENEvxGufxNxxNQY-hJNU',
    appId: '1:828532925773:ios:fabf3e95daa845cdbb8304',
    messagingSenderId: '828532925773',
    projectId: 'calories-scanner-2772d',
    storageBucket: 'calories-scanner-2772d.appspot.com',
    iosBundleId: 'com.ai.caloriescanner.calorietracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7-Ws-pge9gDENEvxGufxNxxNQY-hJNU',
    appId: '1:828532925773:ios:46cbe27090faf4a3bb8304',
    messagingSenderId: '828532925773',
    projectId: 'calories-scanner-2772d',
    storageBucket: 'calories-scanner-2772d.appspot.com',
    iosBundleId: 'com.example.caloriesDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh6dDpy_Ag1opwALIujaCl6fWbMdz1lKQ',
    appId: '1:828532925773:web:5e26c549f2c0f465bb8304',
    messagingSenderId: '828532925773',
    projectId: 'calories-scanner-2772d',
    authDomain: 'calories-scanner-2772d.firebaseapp.com',
    storageBucket: 'calories-scanner-2772d.appspot.com',
    measurementId: 'G-M6Z8ZTW26D',
  );
}
